language: julia
os:
  - linux
  - osx
julia:
  - 0.5
  - 0.6
  - nightly
matrix:
  allow_failures:
    - julia: nightly
    - os: osx
      julia: 0.5
cache:
 directories:
   - /home/travis/.julia
sudo: false
addons:
  apt_packages:
    - gfortran
    - liblapack-dev
    - libgmp-dev
    - libglpk-dev

before_install:
    # don't keep an old version of the code in the cache
  - julia -e 'if "Katana" in keys(Pkg.installed()) Pkg.rm("Katana"); Pkg.rm("Katana") end'
  - julia -e 'Pkg.update()' #make sure we get the latest version of METADATA
  - julia -e 'if !("Coverage" in keys(Pkg.installed())) Pkg.add("Coverage") end'
  - julia -e 'if !("Documenter" in keys(Pkg.installed())) Pkg.add("Documenter") end'

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd())'
  - julia -e 'Pkg.test("Katana", coverage=true)'

after_success:
  - echo $TRAVIS_JULIA_VERSION

  - julia -e 'using Coverage; cd(Pkg.dir("Katana")); Codecov.submit(process_folder("."));'

  - julia -e 'cd(Pkg.dir("Katana")); include(joinpath("docs", "make.jl"))'
